### ISSUE TITLE
Install

### ISSUE THREAD

**Issue by thesequel** [roshancode/redditclone#1]
How to install?

**Comment by thesequel** [comment]
Because import sql and edit. db.php wont work.
Get this error: ERROR: Could not connect. Access denied for user 'st2014'@'localhost' (using password: YES)

**Comment by roshanlam** [comment]
I believe this a problem from your MySQL server. Since the Error says that it could not connect but I did update my code if it helps in anyway.
But did you have everything set up?
$host = ' '; your hostname
$user = ' '; your username
$pass = ' '; your password
$db = ' '; your database name
